name: deploy

on:
  schedule:
    - cron: "0 4,16 * * *"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

env:
  ACT3_VERSION: v2.0.0

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install act3
        uses: jaxxstorm/action-install-gh-release@6096f2a2bbfee498ced520b6922ac2c06e990ed2 # v2.1.0
        with:
          repo: dhth/act3
          tag: ${{ env.ACT3_VERSION }}
      - name: Generate GH token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.GH_TOKEN_APP_ID }}
          private-key: ${{ secrets.GH_TOKEN_APP_PRIVATE_KEY }}
      - name: Create dist directories
        run: |
          mkdir -p dist dist/reports
      - name: Generate reports
        run: |
          act3 \
            -g \
            -c ./main.yml \
            --html-title "main" \
            --html-template-path templates/report.html \
            -f html > dist/reports/main.html

          act3 \
            -g \
            -c ./pr.yml \
            --html-title "pull requests" \
            --html-template-path templates/report.html \
            -f html > dist/reports/pr.html

          act3 \
            -g \
            -c ./release.yml \
            --html-title "releases" \
            --html-template-path templates/report.html \
            -f html > dist/reports/release.html

          act3 \
            -g \
            -c ./scan.yml \
            --html-title "scans" \
            --html-template-path templates/report.html \
            -f html > dist/reports/scan.html

          act3 \
            -g \
            -c ./vuln.yml \
            --html-title "vulnerability checks" \
            --html-template-path templates/report.html \
            -f html > dist/reports/vuln.html

          cp -r assets/* dist
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
